site_name: IT sikkerhed
site_url: https://mydomain.org/mysite
theme:
  name: material
  font:
    text: JetBrains Mono #Merriweather Sans
  
  palette: 
    
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep orange
      accent: deep orange

      # Light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: deep orange
      accent: deep orange

markdown_extensions:
  - pymdownx.details

extra:
  generator: false

  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/noah-rosenkj%C3%A6r/
    - icon: fontawesome/brands/github
      link: https://github.com/NoahRosenkjaer