site_name: IT sikkerhed
site_url: https://mydomain.org/mysite
theme:
  name: material
  font:
    text: Merriweather Sans
  
  palette: 
    
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep orange
      accent: deep orange

      # Light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: deep orange
      accent: deep orange
  