site_name: IT sikkerhed
site_url: https://noahrosenkjaer.github.io/
theme:
  name: material
  font:
    text: Lexend #JetBrains Mono
    code: JetBrains Mono

  features:
  - content.code.copy

  palette: 
    
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: change to light mode
      primary: black

      # Light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Change to dark mode
      primary: grey

markdown_extensions:
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - admonition

extra:
  generator: false

  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/noah-rosenkj%C3%A6r/
    - icon: fontawesome/brands/github
      link: https://github.com/NoahRosenkjaer